//! `ecdh` is an module used specifically to maintain all `ECDH` operations. This module
//! provides a set of abstractions built on top of `x25519_dalek`
//!
//! The `ECDH` algorithm used to provides a set of `key agreement`, which mean, this algorithm
//! will be able to generate a shared secret key without need to share the private key. The generated
//! shared secret key will be generated by given public key from authorized parties that already
//! exchanged their public keys
pub mod keypair;
pub mod pubkey;
pub mod secret;
pub mod types;
